<a href="https://colab.research.google.com/github/TakashiNishii/CursoIA/blob/main/AutoMLH2O.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Auto ML e Tunning com H2o
Dados disponiveis em: [insurance.csv](https://github.com/TakashiNishii/CursoIA/blob/main/insurance.csv)

In [2]:
!pip install h2o

Collecting h2o
  Downloading h2o-3.46.0.10-py2.py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from h2o) (2.32.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from h2o) (0.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (2026.4.22)
Downloading h2o-3.46.0.10-py2.py3-none-any.whl (266.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.4/266.4 MB 6.6 MB/s eta 0:00:00
Installing collected packages: h2o
Successfully installed h2o-3.46.0.10

In [3]:
import h2o
from h2o.automl import H2OAutoML

In [4]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.18" 2026-01-20; OpenJDK Runtime Environment (build 17.0.18+8-Ubuntu-122.04.1); OpenJDK 64-Bit Server VM (build 17.0.18+8-Ubuntu-122.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpk1w8lx3o
  JVM stdout: /tmp/tmpk1w8lx3o/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpk1w8lx3o/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.10
H2O_cluster_version_age:    1 month and 22 days
H2O_cluster_name:           H2O_from_python_unknownUser_7u1umi
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.168 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.13 final
--------------------------  -----------------------------------------------------------------------------------------

In [5]:
data = h2o.import_file('insurance.csv')

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [6]:
data

  C1  GoodStudent    Age         SocioEcon    RiskAversion    VehicleYear    ThisCarDam    RuggedAuto    Accident    MakeModel    DrivQuality    Mileage     Antilock    DrivingSkill    SeniorTrain    ThisCarCost    Theft    CarValue    HomeBase    AntiTheft    PropCost     OtherCarCost    OtherCar    MedCost    Cushioning    Airbag    ILiCost    DrivHist
----  -------------  ----------  -----------  --------------  -------------  ------------  ------------  ----------  -----------  -------------  ----------  ----------  --------------  -------------  -------------  -------  ----------  ----------  -----------  -----------  --------------  ----------  ---------  ------------  --------  ---------  ----------
   1  False          Adult       Prole        Adventurous     Older          Moderate      EggShell      Mild        Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        True        Thousand   Poor          False     Thousand   Many
   2  False          Senior      Prole        Cautious        Current        None          Football      None        Economy      Normal         TwentyThou  False       Normal          True           Thousand       False    TenThou     City        True         Thousand     Thousand        True        Thousand   Good          True      Thousand   Zero
   3  False          Senior      UpperMiddle  Psychopath      Current        None          Football      None        FamilySedan  Excellent      Domino      True        Normal          False          Thousand       False    TwentyThou  City        False        Thousand     Thousand        False       Thousand   Good          True      Thousand   One
   4  False          Adolescent  Middle       Normal          Older          None          EggShell      None        Economy      Normal         FiftyThou   False       Normal          False          Thousand       False    FiveThou    Suburb      False        Thousand     Thousand        True        Thousand   Fair          False     Thousand   Zero
   5  False          Adolescent  Prole        Normal          Older          Moderate      Football      Moderate    Economy      Poor           FiftyThou   False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        False       Thousand   Fair          False     Thousand   Many
   6  False          Adult       UpperMiddle  Normal          Current        Moderate      EggShell      Moderate    SportsCar    Poor           FiftyThou   True        SubStandard     False          HundredThou    False    TwentyThou  Suburb      True         HundredThou  HundredThou     True        TenThou    Poor          True      Thousand   Many
   7  False          Senior      UpperMiddle  Normal          Current        Mild          Football      Mild        Economy      Poor           FiveThou    False       SubStandard     False          TenThou        False    TenThou     Secure      True         TenThou      Thousand        False       Thousand   Excellent     True      Thousand   Many
   8  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    TenThou     City        False        Million      HundredThou     True        Thousand   Fair          False     Thousand   Many
   9  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        HundredThou  TenThou         False       TenThou    Poor          False     Thousand   Many
  10  True           Adolescent  Prole        Cautious        Older          Severe        Football      Severe      FamilySedan  Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        True         HundredThou  HundredThou     True        Thousand   Good          False     Thousand   Many
[20000 rows x 28 columns]

In [7]:
data = data.drop("C1")

In [8]:
treino, teste = data.split_frame(ratios=[0.7], seed=0)

In [11]:
model_automl = H2OAutoML(max_runtime_secs=180, sort_metric='AUTO')
model_automl.train(y='Accident', training_frame=treino)

AutoML progress: |█████████████████
23:05:08.824: GLM_1_AutoML_2_20260504_230420 [GLM def_1] failed: java.lang.ArrayIndexOutOfBoundsException: Index 83 out of bounds for length 83

██████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OStackedEnsembleEstimator : Stacked Ensemble
Model Key: StackedEnsemble_BestOfFamily_1_AutoML_2_20260504_230420


Model Summary for Stacked Ensemble:
key                                   value
------------------------------------  ----------------
Stacking strategy                     cross_validation
Number of base models (used / total)  2/2
# GBM base models (used / total)      1/1
# XGBoost base models (used / total)  1/1
Metalearner algorithm                 GLM
Metalearner fold assignment scheme    Random
Metalearner nfolds                    5
Metalearner fold_column
Custom metalearner hyperparameters    None

ModelMetricsMultinomialGLM: stackedensemble
** Reported on train data. **

MSE: 0.02920272494678528
RMSE: 0.17088804799278762
LogLoss: 0.09914840276436247
Null degrees of freedom: 10048
Residual degrees of freedom: 10024
Null deviance: 18239.82261961006
Residual deviance: 1992.6845987581569
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error       Rate
------  ----------  ------  --------  ----------  ------------
711     55          118     0         0.195701    173 / 884
33      621         3       128       0.208917    164 / 785
12      0           7165    0         0.00167201  12 / 7,177
0       38          0       1165      0.0315877   38 / 1,203
756     714         7286    1293      0.0385113   387 / 10,049

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.961489
2    0.999502
3    1
4    1

ModelMetricsMultinomialGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 0.039012183743394734
RMSE: 0.19751502156391734
LogLoss: 0.13416394090607595
Null degrees of freedom: 14063
Residual degrees of freedom: 14038
Null deviance: 25520.491832222382
Residual deviance: 3773.7633298061046
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error       Rate
------  ----------  ------  --------  ----------  ------------
924     105         192     1         0.243863    298 / 1,222
66      846         3       213       0.25        282 / 1,128
35      0           10017   0         0.00348189  35 / 10,052
0       106         0       1556      0.0637786   106 / 1,662
1025    1057        10212   1770      0.0512656   721 / 14,064

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.948734
2    0.998862
3    1
4    1

Cross-Validation Metrics Summary:
                         mean       sd          cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ---------  ----------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.9487     0.00497393  0.957372      0.946518      0.948325      0.945896      0.945385
aic                      nan        0           nan           nan           nan           nan           nan
auc                      nan        0           nan           nan           nan           nan           nan
err                      0.0513005  0.00497393  0.0426275     0.0534817     0.051675      0.0541038     0.0546146
err_count                144.2      13.3679     122           149           145           147           158
loglikelihood            0          0           0             0             0             0             0
logloss                  0.134215   0.00456089  0.127496      0.138362      0.131981      0.138088      0.135149
max_per_class_error      0.26493    0.0319776   0.221239      0.308333      0.251121      0.270042      0.273913
mean_per_class_accuracy  0.859946   0.0130979   0.88111       0.848781      0.862452      0.857517      0.849873
mean_per_class_error     0.140054   0.0130979   0.11889       0.151219      0.137548      0.142483      0.150127
mse                      0.0390371  0.00226238  0.0354697     0.0402097     0.0383161     0.0413014     0.0398887
null_deviance            5104.1     125.297     5083.16       5108.11       5037.01       4981.31       5310.9
pr_auc                   nan        0           nan           nan           nan           nan           nan
r2                       0.926013   0.0021756   0.929231      0.924939      0.925924      0.923357      0.926613
residual_deviance        754.753    21.4706     729.786       770.95        740.68        750.373       781.974
rmse                     0.19751    0.0057874   0.188334      0.200524      0.195745      0.203227      0.199722

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [12]:
ranking = model_automl.leaderboard
ranking = ranking.as_data_frame()
ranking

/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

,model_id,mean_per_class_error,logloss,rmse,mse
0,StackedEnsemble_BestOfFamily_1_AutoML_2_202605...,0.140281,0.134164,0.197515,0.039012
1,GBM_1_AutoML_2_20260504_230420,0.141504,0.139223,0.198193,0.039280
2,XGBoost_1_AutoML_2_20260504_230420,0.143298,0.137838,0.199083,0.039634
3,GBM_3_AutoML_2_20260504_230420,0.146911,0.790582,0.544166,0.296116
4,XGBoost_2_AutoML_2_20260504_230420,0.148301,0.910342,0.595949,0.355155
5,GBM_2_AutoML_2_20260504_230420,0.148865,0.795026,0.546125,0.298252
6,StackedEnsemble_BestOfFamily_2_AutoML_2_202605...,0.152289,0.176814,0.219676,0.048257
7,GBM_4_AutoML_2_20260504_230420,0.157011,0.952838,0.612490,0.375145
8,DRF_1_AutoML_2_20260504_230420,0.214557,2.254385,0.281427,0.079201

In [13]:
prever = model_automl.leader.predict(teste)
prever

stackedensemble prediction progress: |███████████████████████████████████████████| (done) 100%

predict           Mild     Moderate         None       Severe
---------  -----------  -----------  -----------  -----------
None       0.000997397  1.24575e-05  0.998984     5.93523e-06
Moderate   0.0118126    0.978964     0.00016389   0.00905937
Severe     0.00114616   0.0600778    0.000538488  0.938238
None       0.00137994   3.05013e-05  0.998572     1.77676e-05
Severe     0.00693591   0.344055     0.00175823   0.647251
None       0.00497297   7.11419e-05  0.994925     3.07387e-05
Mild       0.980244     0.0164244    0.00304878   0.000282893
None       0.000675964  9.6386e-06   0.999309     5.47271e-06
None       0.00288334   5.18326e-05  0.997038     2.72368e-05
Severe     0.00150372   0.112171     0.000525002  0.8858
[5936 rows x 5 columns]